use master
CREATE DATABASE FlowerShop
go
use FlowerShop
go
CREATE TABLE Customer(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(100) NOT NULL,
	Phone NVARCHAR(50) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	Password NVARCHAR(50) NOT NULL
)
go
CREATE TABLE Category(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(50) NOT NULL
)
go
CREATE TABLE City (
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(200) NOT NULL,
)
go
CREATE TABLE Good (
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(200) NOT NULL,
	Price INT  NOT NULL,
	Quantity INT NOT NULL,
	IdCategory INT NOT NULL,
	FOREIGN KEY (IdCategory) REFERENCES Category(Id),
)
go
CREATE TABLE Orders (
	Id INT PRIMARY KEY IDENTITY,
	IdCustomer INT  NOT NULL,
	TotalPrice INT NOT NULL,
	OrderDate Date NOT NULL,
	FOREIGN KEY (IdCustomer) REFERENCES Customer(Id)
)
go
CREATE TABLE OrderDetails (
	Id INT PRIMARY KEY IDENTITY,
	IdOrder INT NOT NULL,
	IdGood INT NOT NULL,
	Quantity INT NOT NULL,
	Price INT NOT NULL,
	FOREIGN KEY (IdOrder) REFERENCES Orders(Id),
	FOREIGN KEY (IdGood) REFERENCES Good(Id)
)
go
CREATE TABLE Provider (
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(150) NOT NULL,
	IdCity INT NOT NULL,
	Phone NVARCHAR(50) NOT NULL,
	Email NVARCHAR(150) NOT NULL,
	FOREIGN KEY (IdCity) REFERENCES City(Id),
)
go
CREATE TABLE Supply (
	Id INT PRIMARY KEY IDENTITY,
	IdProvider INT NOT NULL,
	IdGood INT NOT NULL,
	Quantity INT NOT NULL,
	DateSupply DATE NOT NULL,
	FOREIGN KEY (IdProvider) REFERENCES Provider(Id),
	FOREIGN KEY (IdGood) REFERENCES Good(Id)
)