//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyLog
    {
        public int Id { get; set; }
        public Nullable<int> IdSupply { get; set; }
        public string LogMessage { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
    }
}
